### ISSUE TITLE
Me endpoint

### ISSUE THREAD

**Issue by RumbosN** [ebx/ebx-linkedin-sdk#103]
Hi,

I need to do a request to the [me endpoint](https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api?context=linkedin/compliance/context) but I can't find how do that with the library.

Dose anyone have an idea of how to do it?

**Comment by RumbosN** [comment]
Update:
`client.webRequestor.executeGet("https://api.linkedin.com/v2/me")` give me the me object

When I try with `client.fetchConnection("/me", JsonNode::class.java)` throw a null pointer exception in `jsonObject.get(pagingStrategy.getDataKey()).asArray();` in the file Connection.java line 170

`pagingStrategy.getDataKey()` is "elements" but the jsonObject not is a group of elements, it has the next form
```
{
  "localizedLastName":"something",
  "lastName":{
    "localized":{
      "en_US":"something"
    },
    "preferredLocale":{
      "country":"US",
      "language":"en"
    }
  },
  "firstName":{
    "localized":{"en_US":"Daniela"},
    "preferredLocale":{"country":"US","language":"en"}
  },
  "id":"something",
  "localizedFirstName":"something"
}
```

**Comment by diepjy** [comment]
Hi,

Thank you very much for raising this issue - the Profile LinkedIn API has not been added to the project yet. 

If you would to raise a PR to add this API you are more than welcome to by following the [contributions guide](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md).

**Comment by djjashton** [comment]
Closing as this issue is based on the old unversioned API that is no longer available.
