### ISSUE TITLE
Upload mapping error

### ISSUE THREAD

**Issue by wutsi** [ebx/ebx-linkedin-sdk#119]
I'm trying to upload an asset and I received the following error
```
com.echobox.api.linkedin.exception.LinkedInQueryParseException: Received LinkedIn error response: Parameters of method 'registerUpload' failed validation with error 'ERROR :: /registerUploadRequest/supportedUploadMechanism :: array type is not backed by a DataList
Dec 28 16:30:32 int-com-wutsi-blog app/web.1 ' (code null)
Dec 28 16:30:32 int-com-wutsi-blog app/web.1 	at com.echobox.api.linkedin.client.DefaultLinkedInClient$DefaultLinkedInExceptionMapper.exceptionForTypeAndMessage(DefaultLinkedInClient.java:720)
Dec 28 16:30:32 int-com-wutsi-blog app/web.1 	at com.echobox.api.linkedin.client.DefaultLinkedInClient.throwLinkedInResponseStatusExceptionIfNecessary(DefaultLinkedInClient.java:698)
Dec 28 16:30:32 int-com-wutsi-blog app/web.1 	at com.echobox.api.linkedin.client.DefaultLinkedInClient.makeRequestAndProcessResponse(DefaultLinkedInClient.java:638)
....
```

Looking at linked in specs [here](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/vector-asset-api#register-an-upload-for-images)
- Looks like `supportedUploadMechanism` should be a list
- But `RegisterUploadRequestBody.supportedUploadMechanism` is not in the code.
- 
Is this the issue?

**Comment by diepjy** [comment]
Hi wutsi,

Thanks for raising this issue - indeed the `RegisterUploadRequestBody.supportedUploadMechanism` should be an a List  - we have added this to the backlog.

If you would to raise a PR to add this API you are more than welcome to by following the [contributions guide](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md).

**Comment by wutsi** [comment]
will do

**Comment by wutsi** [comment]
@diepjy can you grant me access to the repo.
My PR for the fix is ready

**Comment by wutsi** [comment]
@diepjy @MarcFletcher can you grant me access to the codebase so that I can submit the fix for this issue?
I have the PR ready locally
Thank you

**Comment by diepjy** [comment]
@wutsi - you should be able to create a PR by forking the repository, make the change in your repo and then raise the pull request in https://github.com/ebx/ebx-linkedin-sdk/pulls against your local fork, to be merged into this repo.

Please follow our [contributions guideline](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md) when raising a pull request.

**Comment by wutsi** [comment]
@diepjy PR opened: https://github.com/ebx/ebx-linkedin-sdk/pull/122

**Comment by diepjy** [comment]
Many thanks for raising both the issue and the PR - the PR has now been merged as part of the 2.0.1-SNAPSHOT.

**Comment by wutsi** [comment]
@diepjy when is `2.0.1` will ve available?

**Comment by diepjy** [comment]
@wutsi many thanks for raising the PR, the version `2.0.1` is now available.
