### ISSUE TITLE
Access feed with posts for connected user posts

### ISSUE THREAD

**Issue by Artgit** [ebx/ebx-linkedin-sdk#121]
Hello and thanks for your great library!

I have a general question:
At the home page of my personal LinkedIn account https://www.linkedin.com/feed/ I can see the feed with all posts of all connected users.

Is it possible to access such posts via LinkedIn API and your library ? if so, could you please point me to appropriate API documentation or example? Thanks!

**Comment by diepjy** [comment]
Hi Artgit,

It should be possible to get the posts from a LinkedIn feed using [UGC Post API](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api) and the [Shares API](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api). You can see the methods in [ShareConnection.getShares](https://github.com/ebx/ebx-linkedin-sdk/blob/dev/src/main/java/com/echobox/api/linkedin/connection/v2/ShareConnection.java) and [UGCShareConnection.retrieveUGCPostsByAuthors](https://github.com/ebx/ebx-linkedin-sdk/blob/dev/src/main/java/com/echobox/api/linkedin/connection/v2/UGCShareConnection.java) providing you have the URN of the owner of the feed.

Thanks.
