### ISSUE TITLE
Unable to Post with a loaded videos=

### ISSUE THREAD

**Issue by RumbosN** [ebx/ebx-linkedin-sdk#126]
I can load the video with `RegisterUploadRequestBody.RecipeURN.FEED_SHARE_VIDEO` in the endpoint `assetsConnection.uploadImageAsset`. 

But then when I try to post, in the `UGCShare` putting in the `ShareContentBody()` the attribute `contentBody.shareMediaCategory = LinkedInConstants.SHARE_MEDIA_CATEGORY_VIDEO` the service response is `Received LinkedIn error response: LinkedIn request failed (code null)` 

For now I'm using **SHARE_MEDIA_CATEGORY_IMAGE** instead **SHARE_MEDIA_CATEGORY_VIDEO** to post a image of the video instead of the video. But I need to post the Video as a Video.

**Comment by diepjy** [comment]
@RumbosN 

Many thanks for raising this issue - we have added this to the backlog. As LinkedIn recently made their video upload endpoints available for all LinkedIn apps we can now test this endpoint.

If you would to raise a PR to add this API you are more than welcome to by following the [contributions guide](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md).

**Comment by djjashton** [comment]
Closing as this issue is based on the old unversioned API that is no longer available.
