### ISSUE TITLE
Problems with share IMAGE

### ISSUE THREAD

**Issue by joergrech** [ebx/ebx-linkedin-sdk#130]
Hi, can you give me an example for sharing an Image with a post? I can upload a text post with the example from the README but I failed at adding an image to the shareContent object.

**Comment by diepjy** [comment]
@joergrech 

You first have to upload the image to LinkedIn via their [vector assets API](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/vector-asset-api) - which you can do via `AsseetsConnection.uploadImageAsset`.

Once the image has been uploaded successfully and the digital asset URN is returned, you can create the UGC post (see [example](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api#create-ugc-posts)) using `UGCShareConnection` as part of the request body and include the digital asset URN in the media field i.e:
```
"specificContent": {
        "com.linkedin.ugc.ShareContent": {
            "media": [
                {
                    "media": "urn:li:digitalmediaAsset:C5500AQG7r2u00ByWjw", <--- uploaded digital media asset
                    "status": "READY",
                    "title": {
                        "attributes": [],
                        "text": "Sample Video Create"
                    }
                }
            ],
            "shareCommentary": {
                "attributes": [],
                "text": "Some share text"
            },
            "shareMediaCategory": "IMAGE"
        }
    },
```
