### ISSUE TITLE
Unable to collect Statistics for UGC post.

### ISSUE THREAD

**Issue by shrinidhid** [ebx/ebx-linkedin-sdk#131]
Unable to collect Statistics for UGC post since the URNEntityType is expected to be of Type SHARE whereas I'm trying to collect the stats for an UGC post. Is there a method to find the Stats for an UGC Post or should ebx-linkedin-sdk be updated for this?

`The URN should be type SHARE
	at com.echobox.api.linkedin.connection.ConnectionBase.validateURN(ConnectionBase.java:86)
	at com.echobox.api.linkedin.connection.v2.ConnectionBaseV2.validateShareURN(ConnectionBaseV2.java:103)`

**Comment by diepjy** [comment]
@shrinidhid 

Unfortunately LinkedIn's [organisation share statistics API](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/share-statistics) only applies to SHARE URNs rather than UGC URNs.

**Comment by shrinidhid** [comment]
May I know if there is an equivalent for the below API ? `https://api.linkedin.com/v2/organizationalEntityShareStatistics?q=organizationalEntity&organizationalEntity=urn:li:organization:2414183&ugcPosts[0]=urn:li:ugcPost:1000000&ugcPosts[1]=urn:li:ugcPost:1000001 `

**Comment by diepjy** [comment]
Unfortunately there's no documentation on LinkedIn's API to suggest this.

**Comment by shrinidhid** [comment]
@diepjy Please find the API I was referring to in the below Screenshot. This is from the same link [organisation share statistics API](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/share-statistics) provided above.
![image](https://user-images.githubusercontent.com/62990964/108492786-7a2af680-729d-11eb-91e2-ab9a7743416b.png)

**Comment by diepjy** [comment]
@shrinidhid - thanks for noticing the update on the documentation, when we implemented the endpoint it was not available for UGC posts. 

We have added this to the backlog. If you would to raise a PR to add this API you are more than welcome to by following the [contributions guide](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md).

**Comment by diepjy** [comment]
@shrinidhid - if you would like to raise a PR for this issue, we'll integrate that into our next release :)

**Comment by djjashton** [comment]
Closing as this issue is based on the old unversioned API that is no longer available.
