### ISSUE TITLE
Unable to post any of the data type in jsonbody other than string

### ISSUE THREAD

**Issue by badCODERever** [ebx/ebx-linkedin-sdk#139]
When I am trying to create a new campaign using create campaign API, sending the runschedule as long format `"runSchedule": {
        "end": 1624329157,
        "start": 1622601157
    }`
    
    but defaultclient is throwing an error like this for date and boolean data type
    
    `{"errorDetailType":"com.linkedin.common.error.BadRequest","message":"Multiple errors occurred during the input validation. Please see errorDetails for more information.","errorDetails":{"inputErrors":[{"description":"ERROR :: /runSchedule/start :: {} cannot be coerced to Long","input":{"inputPath":{"fieldPath":"/Campaign/runSchedule/start"}},"code":"INVALID_VALUE"},{"description":"Invalid value for field; wrong type or otherwise invalid input","input":{"inputPath":{"fieldPath":"/runSchedule/start"}},"code":"INVALID_VALUE"}]},"status":400}`
    
    may I know what is the issue, why this is happening and If you could give me the documentation impl examples for each method call GET, POST, PUT that would be great.

**Comment by am6010** [comment]
A fix was added in version 3.0.4 .
