### ISSUE TITLE
Integration with Post API

### ISSUE THREAD

**Issue by danielavelasquezc** [ebx/ebx-linkedin-sdk#270]
LinkedIn request migrate to [POST API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api?view=li-lms-2022-07)

Currently the library use [UgcPosts](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api?view=li-lms-2022-07) and Shares but both going to be deprecated on Feb 2023

https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/contentapi-migration-guide?trk=eml-mktg-20221116-api-november-2022-email-global&mcid=6996157665512996865&src=e-eml&view=li-lms-2022-07

**Comment by djjashton** [comment]
Updating to use the new versioned API is in progress.
