### ISSUE TITLE
JSONUtils.getValue() should support booleans

### ISSUE THREAD

**Issue by rjgithub2** [ebx/ebx-linkedin-sdk#274]
This is needed for processing boolean fields within the request bodies of certain calls like [the videos initializeUpload call](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/videos-api?view=li-lms-2022-12&tabs=http#initialize-video-upload).

The method needs a clause similar to:

```
        } else if (jsonValue.isBoolean()) {
            value = jsonValue.asBoolean();
        }
```

**Comment by kennethwong-hc** [comment]
Hi @rjgithub2 , thanks for your suggestion. This will be included in the next release
