### ISSUE TITLE
DefaultLinkedInExceptionMapper needs a public constructor

### ISSUE THREAD

**Issue by rjgithub2** [ebx/ebx-linkedin-sdk#275]
The DefaultLinkedInExceptionMapper inner class within DefaultVersionedLinkedInClient.java and DefaultLinkedInClient.java should have a public constructor.   Without it, subclasses of those client classes that want to call super constructors that take a LinkedInExceptionMapper parameter can't instantiate DefaultLinkedInExceptionMapper if they want to use that.

In particular, the only DefaultVersionedLinkedInClient constructor that allows the versionedMonth to be overridden can't currently be called without also specifying a non-default LinkedInExceptionMapper.

**Comment by kennethwong-hc** [comment]
Hi @rjgithub2 ,  thanks for your suggestion. This will be included in the next release
