### ISSUE TITLE
Duplicate id definition in Post and LinkedInURNIdType

### ISSUE THREAD

**Issue by xberger** [ebx/ebx-linkedin-sdk#344]
Hi,

for some reason I wanted to deserialize a json string to the `com.echobox.api.linkedin.types.posts.Post` class with Gson and I got the following error message:
`java.lang.IllegalArgumentException: class com.echobox.api.linkedin.types.posts.Post declares multiple JSON fields named id`

Turns out, the field `private URN id;` is definied both in the `Post` class and in it's base class `LinkedInURNIdType`. Does this have a reason or would it be sufficient to just have the field in the latter class? As far as I understand that is what base classes are for, to just have it in one place.

Definition in the `Post` class:
```
  /**
   * ugcPostUrn or shareUrn
   */
  @Getter
  @Setter
  @LinkedIn
  private URN id;
```  

Definition in the `LinkedInURNIdType` class:

```
   /**
   * Unique id for this object. Can contain more urn types in the future.
   */
  @Getter
  @LinkedIn("id")
  private URN id;
```  

Best regards,
xberger

**Comment by djjashton** [comment]
Hi

Thank you for raising this issue. It has been added to our backlog of work.

If you would to raise a PR to resolve this you are more than welcome to by following the [contributions guide](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md).

**Comment by jack7ellis** [comment]
@xberger this issue has been resolved in [this](https://github.com/ebx/ebx-linkedin-sdk/pull/388) PR, which was deployed in version `4.6.0` of the SDK.

Thanks for raising the issue.

**Comment by jack7ellis** [comment]
@xberger https://github.com/ebx/ebx-linkedin-sdk/pull/388 issue has been resolved in this PR, which was deployed in version 4.6.0 of the SDK.

Thanks for raising the issue.
